import { type ReactNode } from 'react'

import { ConfidenceMark } from './ui/Card'

/**
 * A renderer for the markdown the coach actually writes, and nothing else.
 *
 * The profile is generated by a model we prompt, into a structure we specify:
 * `## headings`, bullet lists, short paragraphs, and `**bold**` for the
 * occasional lead-in. A full CommonMark parser would be several hundred
 * kilobytes to handle link reference definitions and setext headings that will
 * never appear. Anything unrecognised falls through as plain text rather than
 * disappearing, which is the failure mode that matters — a fact the user is
 * relying on must never be silently swallowed by a parser.
 *
 * No `dangerouslySetInnerHTML` anywhere: every branch returns React elements, so
 * markup in a profile renders as the characters it is.
 */

/** `**bold**` and `*italic*`, non-greedy, left to right. */
const INLINE = /(\*\*[^*]+\*\*|\*[^*]+\*)/g

function inline(text: string): ReactNode[] {
  return text.split(INLINE).map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**') && part.length > 4) {
      return (
        <strong key={i} className="font-semibold text-fg">
          {part.slice(2, -2)}
        </strong>
      )
    }
    if (part.startsWith('*') && part.endsWith('*') && part.length > 2) {
      return <em key={i}>{part.slice(1, -1)}</em>
    }
    return part
  })
}

/**
 * A trailing `(high)` / `(medium)` / `(low)` is how a rebuild carries confidence
 * in prose, since the markdown has no field for it. Pulled back out here so it
 * renders as the same mark the structured view used, rather than as literal
 * text at the end of every bullet.
 */
// Trailing turn citations are allowed to follow it — "…a small studio (high) [2]"
// is exactly what the prompt asks for, and anchoring hard to the end of the line
// left half the bullets showing "(high)" as literal text. The citations are put
// back; only the confidence is lifted out.
const CONFIDENCE = /\s*\((high|medium|low)\)(\s*(?:\[[\d,\s]+\]\s*)*)$/i

function Bullet({ text }: { text: string }) {
  const match = text.match(CONFIDENCE)
  const level = match?.[1]?.toLowerCase() as 'high' | 'medium' | 'low' | undefined
  const body = level ? text.replace(CONFIDENCE, '$2').trimEnd() : text

  return (
    <li className="flex gap-2 text-[12.5px] leading-relaxed text-fg-2">
      <span className="mt-1.5 h-1 w-1 flex-none rounded-full bg-neutral-300" />
      <span className="min-w-0 flex-1">
        {inline(body)}
        {level ? (
          <span className="ml-1.5">
            <ConfidenceMark level={level} />
          </span>
        ) : null}
      </span>
    </li>
  )
}

type Chunk =
  | { kind: 'heading'; text: string }
  | { kind: 'list'; items: string[] }
  | { kind: 'para'; text: string }

const HEADING = /^#{1,6}\s+(.*)$/
const BULLET = /^\s*[-*]\s+(.*)$/

function chunk(markdown: string): Chunk[] {
  const chunks: Chunk[] = []
  let list: string[] | null = null
  let para: string[] | null = null

  const flush = () => {
    if (list?.length) chunks.push({ kind: 'list', items: list })
    if (para?.length) chunks.push({ kind: 'para', text: para.join(' ') })
    list = null
    para = null
  }

  for (const line of markdown.split('\n')) {
    const heading = line.match(HEADING)
    if (heading) {
      flush()
      chunks.push({ kind: 'heading', text: heading[1]!.trim() })
      continue
    }
    const bullet = line.match(BULLET)
    if (bullet) {
      if (para) flush()
      list ??= []
      list.push(bullet[1]!.trim())
      continue
    }
    if (!line.trim()) {
      flush()
      continue
    }
    if (list) flush()
    para ??= []
    para.push(line.trim())
  }
  flush()
  return chunks
}

export function Markdown({ children }: { children: string }) {
  const chunks = chunk(children)
  if (!chunks.length) return null

  return (
    <div className="space-y-4">
      {chunks.map((c, i) => {
        if (c.kind === 'heading') {
          return (
            <h3
              key={i}
              className="border-b border-border pb-1.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-fg-3 first:mt-0 [&:not(:first-child)]:mt-6"
            >
              {c.text}
            </h3>
          )
        }
        if (c.kind === 'list') {
          return (
            <ul key={i} className="space-y-1.5">
              {c.items.map((item, j) => (
                <Bullet key={j} text={item} />
              ))}
            </ul>
          )
        }
        return (
          <p key={i} className="text-[12.5px] leading-relaxed text-fg-2">
            {inline(c.text)}
          </p>
        )
      })}
    </div>
  )
}
