import { type ReactNode } from 'react'

import { ConfidenceMark } from './ui/Card'

/**
 * A renderer for the markdown the coach actually writes, and nothing else.
 *
 * The profile is generated by a model we prompt, into a structure we specify:
 * `## headings`, bullet lists, short paragraphs, and `**bold**` for the
 * occasional lead-in. A full CommonMark parser would be several hundred
 * kilobytes to handle link reference definitions and setext headings that will
 * never appear. Anything unrecognised falls through as plain text rather than
 * disappearing, which is the failure mode that matters — a fact the user is
 * relying on must never be silently swallowed by a parser.
 *
 * No `dangerouslySetInnerHTML` anywhere: every branch returns React elements, so
 * markup in a profile renders as the characters it is.
 */

/** `**bold**` and `*italic*`, non-greedy, left to right. */
const INLINE = /(\*\*[^*]+\*\*|\*[^*]+\*)/g

function inline(text: string): ReactNode[] {
  return text.split(INLINE).map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**') && part.length > 4) {
      return (
        <strong key={i} className="font-semibold text-fg">
          {part.slice(2, -2)}
        </strong>
      )
    }
    if (part.startsWith('*') && part.endsWith('*') && part.length > 2) {
      return <em key={i}>{part.slice(1, -1)}</em>
    }
    return part
  })
}

/**
 * A trailing `(high)` / `(medium)` / `(low)` is how a rebuild carries confidence
 * in prose, since the markdown has no field for it. Pulled back out here so it
 * renders as the same mark the structured view used, rather than as literal
 * text at the end of every bullet.
 */
// Trailing turn citations are allowed to follow it — "…a small studio (high) [2]"
// is exactly what the prompt asks for, and anchoring hard to the end of the line
// left half the bullets showing "(high)" as literal text. The citations are put
// back; only the confidence is lifted out.
const CONFIDENCE = /\s*\((high|medium|low)\)(\s*(?:\[[\d,\s]+\]\s*)*)$/i

function Bullet({ text, marker }: { text: string; marker?: string }) {
  const match = text.match(CONFIDENCE)
  const level = match?.[1]?.toLowerCase() as 'high' | 'medium' | 'low' | undefined
  const body = level ? text.replace(CONFIDENCE, '$2').trimEnd() : text

  return (
    <li className="flex gap-2 text-[12.5px] leading-relaxed text-fg-2">
      {marker ? (
        <span className="tabular mt-px w-3.5 flex-none text-right font-mono text-[11px] text-neutral-400">
          {marker}
        </span>
      ) : (
        <span className="mt-1.5 h-1 w-1 flex-none rounded-full bg-neutral-300" />
      )}
      <span className="min-w-0 flex-1">
        {inline(body)}
        {/* Bound to the text with a non-breaking space: as an ordinary inline
            child the mark could wrap on its own, leaving three glyphs stranded
            on a line under the bullet they belong to. */}
        {level ? (
          <span className="whitespace-nowrap">
            {' '}
            <ConfidenceMark level={level} />
          </span>
        ) : null}
      </span>
    </li>
  )
}

type Chunk =
  | { kind: 'heading'; text: string }
  | { kind: 'list'; items: string[]; markers?: string[] }
  | { kind: 'para'; text: string }

const HEADING = /^#{1,6}\s+(.*)$/
const BULLET = /^\s*[-*]\s+(.*)$/
// `1.` / `2)`, capped at three digits so a paragraph opening with a year —
// "2026. The year she moves" — stays a paragraph. The written number is kept
// rather than recounted, so what renders always matches the markdown behind it.
const ORDERED = /^\s*(\d{1,3})[.)]\s+(.*)$/
// The hanging indent under a bullet. Checked only after the two list patterns
// have had their turn, so an indented `- ` is still a bullet, not a wrap.
const INDENTED = /^\s+\S/

function chunk(markdown: string): Chunk[] {
  const chunks: Chunk[] = []
  let list: { items: string[]; markers: string[] | null } | null = null
  let para: string[] | null = null

  const flush = () => {
    if (list?.items.length) {
      chunks.push({ kind: 'list', items: list.items, ...(list.markers ? { markers: list.markers } : {}) })
    }
    if (para?.length) chunks.push({ kind: 'para', text: para.join(' ') })
    list = null
    para = null
  }

  // A run of `-` and a run of `1.` are different lists, so switching between
  // them starts a new one instead of appending into whichever came first.
  const item = (text: string, marker: string | null) => {
    if (para) flush()
    if (list && (list.markers === null) !== (marker === null)) flush()
    list ??= { items: [], markers: marker === null ? null : [] }
    list.items.push(text)
    if (marker !== null) list.markers?.push(marker)
  }

  // A wrapped bullet continues its item rather than ending the list. The indent
  // is what says so — one long point written across two lines is one bullet, and
  // treating the second line as a paragraph split the list in half around it.
  // A closure like `item` above, because `list` is only ever assigned inside
  // these and narrowing in the loop body doesn't see it.
  const continues = (text: string): boolean => {
    const items = list?.items
    if (!items?.length) return false
    items[items.length - 1] = `${items[items.length - 1]!} ${text}`
    return true
  }

  for (const line of markdown.split('\n')) {
    const heading = line.match(HEADING)
    if (heading) {
      flush()
      chunks.push({ kind: 'heading', text: heading[1]!.trim() })
      continue
    }
    const bullet = line.match(BULLET)
    if (bullet) {
      item(bullet[1]!.trim(), null)
      continue
    }
    const ordered = line.match(ORDERED)
    if (ordered) {
      item(ordered[2]!.trim(), `${ordered[1]}.`)
      continue
    }
    if (!line.trim()) {
      flush()
      continue
    }
    if (INDENTED.test(line) && continues(line.trim())) continue
    if (list) flush()
    para ??= []
    para.push(line.trim())
  }
  flush()
  return chunks
}

export function Markdown({ children }: { children: string }) {
  const chunks = chunk(children)
  if (!chunks.length) return null

  return (
    <div className="space-y-4">
      {chunks.map((c, i) => {
        if (c.kind === 'heading') {
          return (
            <h3
              key={i}
              className="border-b border-border pb-1.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-fg-3 first:mt-0 [&:not(:first-child)]:mt-6"
            >
              {c.text}
            </h3>
          )
        }
        if (c.kind === 'list') {
          const List = c.markers ? 'ol' : 'ul'
          return (
            <List key={i} className="space-y-1.5">
              {c.items.map((item, j) => (
                <Bullet key={j} text={item} marker={c.markers?.[j]} />
              ))}
            </List>
          )
        }
        return (
          <p key={i} className="text-[12.5px] leading-relaxed text-fg-2">
            {inline(c.text)}
          </p>
        )
      })}
    </div>
  )
}
